- API.md
- test/codebuild-ci/codebuild-ci.test.ts
Added computeType config param for CodeBuild
> feat: update compute type

- API.md
- src/codebuild-ci/index.ts
Updates to ezconstruct codebuild to accept props externally
> feat: expose props for codebuild project

- src/secure-bucket/index.ts
- test/secure-bucket/secure-bucket.test.ts
Fixes #
The policy errors observed during secure bucket creation.
> chore: updating policy

- .projenrc.js
- package.json
Fixes #
Updating the python package name to streamline importing.
> chore: updating py-package naming convention

- API.md
- src/codebuild-ci/index.ts
- test/codebuild-ci/codebuild-ci.test.ts
Ability to add a custom base image for builds
> chore: adding capability to override codebuild image

- API.md
- src/codebuild-ci/index.ts
- src/lib/utils.ts
Fixes #
Ability to specify vpc in codebuild by ID
> chore: adding capability to specify codebuild vpc

- API.md
- src/codebuild-ci/index.ts
- test/codebuild-ci/codebuild-ci.test.ts
Fixes #
Adding additional branches pushes to trigger builds
> chore: adding ability to add multiple triggers on branch pushes events

- .projenrc.ts
- API.md
- README.md
- src/index.ts
- src/lib/utils.ts
- src/stepfunctions/README.md
- src/stepfunctions/serverless-spark-job.ts
- test/lib/utils.test.ts
- test/stepfunctions/multi-job-asl.json
- test/stepfunctions/serverless-spark-job.test.ts
- test/stepfunctions/single-job-asl.json
- test/stepfunctions/some-other-asl.json
- tsconfig.dev.json
Adding support to step functions.
> feat: support for step functions

- API.md
- README.md
- src/stepfunctions/README.md
- src/stepfunctions/serverless-spark-job.ts
Fixes # issues with permission while starting jobs
> fix: permission issues with serverless jobs

- src/stepfunctions/serverless-spark-job.ts
Fixes #
--main to --class spark paramters
> fix: class name parameter

- API.md
- package.json
- src/codebuild-ci/index.ts
- test/codebuild-ci/codebuild-ci.test.ts
- yarn.lock
Fixes # issues with respect to pr merge event. The commit was accidentally deleted
> fix: Pull Request Merge Issue

- API.md
- src/stepfunctions/serverless-spark-job.ts
- test/stepfunctions/serverless-spark-job.test.ts
Fixes # an issue with argument passing to spark
> fix: argument passing logic change

- src/stepfunctions/serverless-spark-job.ts
> fix: argument passing logic extra quotes removed

- src/stepfunctions/serverless-spark-job.ts
Fixes #
Entrypoint assembly jar replacement issue
> fix: argument passing logic replacement issue fix

- API.md
- src/lib/utils.ts
- src/stepfunctions/serverless-spark-job.ts
- test/stepfunctions/serverless-spark-job.test.ts
Fixes #
JSON Path for jobcomplete response modified to meet what "ez-aspects" callback is sending.
> fix: status variable mismatch

- API.md
- README.md
- src/emr/README.md
- src/emr/serverless.ts
- src/index.ts
- test/emr/serverless.test.ts
> feat: CW dashboard in EMR Serverless application.

- API.md
- src/lib/utils.ts
- src/stepfunctions/serverless-spark-job.ts
- test/lib/utils.test.ts
- test/stepfunctions/serverless-spark-job.test.ts
Adding validation to ensures the presence of EntryPointArgs
> feat: adding validation of required input

- src/stepfunctions/serverless-spark-job.ts
- test/stepfunctions/serverless-spark-job.test.ts
adding validation result choice branching
> fix: adding validation result choice branching

- src/stepfunctions/serverless-spark-job.ts
> fix: Payload replacement

- src/stepfunctions/serverless-spark-job.ts
Fixing issues with loadash loading.
> fix: loadash loading issue

- src/stepfunctions/serverless-spark-job.ts
Fixes # string conversion issue from Lambda output
> fix: string conversion issue

- API.md
- src/emr/serverless.ts
- test/stepfunctions/serverless-spark-job.test.ts
Skipping dashboards in EMR serverless
> feat: dashboard skipping in emr serverless

- API.md
- src/secure-bucket/index.ts
- test/secure-bucket/secure-bucket.test.ts
Updated lifecycle policies to be more aggresive
> feat: Adding ability to manage lifecycle

- src/secure-bucket/index.ts
- test/secure-bucket/secure-bucket.test.ts
> feat: Updating lifecycle logic

- API.md
- src/secure-bucket/index.ts
- test/secure-bucket/secure-bucket.test.ts
support for s3 path restrictions
> feat: adding path restriction support

- API.md
- src/stepfunctions/serverless-spark-job.ts
- test/stepfunctions/serverless-spark-job.test.ts
log paths of step functions updated
> feat: updates to Stepfunction log path

- API.md
- src/stepfunctions/serverless-spark-job.ts
- test/stepfunctions/serverless-spark-job.test.ts
used retention to auto create logs if do not exists
> feat: updates to stepfunction log creation logic

- API.md
- src/stepfunctions/serverless-spark-job.ts
> feat: accept log group name from SimpleStepFunction

- API.md
- src/stepfunctions/serverless-spark-job.ts
- test/stepfunctions/serverless-spark-job.test.ts
[Fixes #](feat: accept log group name return value changes)
> feat: accept log group name return value changes

- .projen/deps.json
- .projenrc.ts
- API.md
- package.json
- src/stepfunctions/serverless-spark-job.ts
- test/stepfunctions/serverless-spark-job.test.ts
- yarn.lock
Stepfunction Application Config override transformation bug fix
> feat: Stepfunction Application Config override transformation bug fix

- src/stepfunctions/serverless-spark-job.ts
> feat: nodejs latest runtime
